(()=>{const C=document.querySelector('#game'),X=C.getContext('2d'),$=s=>document.querySelector(s),keys=new Set;let mode='menu',last=0,G;
const fresh=()=>({x:95,y:432,vy:0,f:1,hp:100,rage:25,shards:0,form:0,atk:0,weapon:'spear',hurt:0,boss:false,enemies:[{id:1,x:350,hp:45,max:45,kind:'crawler',hit:0},{id:2,x:565,hp:65,max:65,kind:'spear',hit:0}]});G=fresh();
function show(id){['#menu','#story','#ending'].forEach(s=>$(s).classList.add('hidden'));if(id)$(id).classList.remove('hidden')}
function start(){G=fresh();mode='playing';show();$('#hud').classList.remove('hidden');updateHud()}
function attack(){if(mode==='playing'&&G.atk<=0)G.atk=G.weapon==='spear'?22:15}function swap(){G.weapon=G.weapon==='spear'?'sword':'spear'}function transform(){if(mode==='playing'&&G.rage>=60&&!G.form){G.rage-=60;G.form=360}}
function ending(win){mode=win?'won':'lost';$('#hud').classList.add('hidden');show('#ending');$('#endLabel').textContent=win?'ПРОБНАЯ ГЛАВА ПРОЙДЕНА':'ВРЕМЕННАЯ ЛИНИЯ ОБОРВАНА';$('#endTitle').textContent=win?'Разрыв открыт':'Мы всё умрём!';$('#endText').textContent=win?'Кан вступает в Междумирье. Голос Мор-Кэра уже ждёт его по ту сторону…':'Сфера времени даёт Кану ещё одну попытку.'}
function updateHud(){const hp=Math.max(0,Math.round(G.hp)),r=Math.round(G.rage);$('#hp').style.width=hp+'%';$('#hpText').textContent=hp+'%';$('#rage').style.width=r+'%';$('#rageText').textContent=r+'%';$('#weapon').textContent=G.weapon==='spear'?'Копьё':'Меч';$('#shards').textContent='◆ '+G.shards;$('#objective').textContent=G.boss?(G.enemies.length?'Победите Хроножора':'Войдите в портал'):'Победите стражей разрыва'}
function hero(){const m=G.form>0,x=G.x,y=G.y,f=G.f;X.save();X.translate(x,y);X.scale(f,1);if(G.hurt>0)X.globalAlpha=.55;X.strokeStyle=m?'#e30624':'#f4f1ea';X.fillStyle='#08080a';X.lineWidth=m?10:7;X.lineCap='round';X.beginPath();X.arc(0,-112,m?22:18,0,7);X.fill();X.stroke();X.strokeStyle='#e30624';X.lineWidth=4;X.beginPath();X.moveTo(-11,-114);X.lineTo(-3,-109);X.moveTo(11,-114);X.lineTo(3,-109);X.stroke();if(m){X.beginPath();X.moveTo(-13,-132);X.lineTo(-25,-153);X.lineTo(-5,-137);X.moveTo(13,-132);X.lineTo(25,-153);X.lineTo(5,-137);X.stroke()}X.strokeStyle=m?'#e30624':'#111';X.lineWidth=m?11:8;X.beginPath();X.moveTo(0,-91);X.lineTo(0,-39);X.moveTo(0,-80);X.lineTo(-48,-45);X.moveTo(0,-80);X.lineTo(55,-53);X.moveTo(0,-39);X.lineTo(-34,0);X.moveTo(0,-39);X.lineTo(40,0);X.stroke();X.fillStyle='#b40820';X.beginPath();X.moveTo(-3,-91);X.lineTo(-58,-72);X.lineTo(-16,-51);X.lineTo(-60,-28);X.lineTo(-6,-39);X.fill();X.strokeStyle='#ddd';X.lineWidth=5;if(G.atk>0)X.rotate(-.55);X.beginPath();X.moveTo(39,-55);X.lineTo(G.weapon==='spear'?116:88,G.weapon==='spear'?-112:-93);X.stroke();X.restore()}
function enemy(e,t){const b=e.kind==='boss';X.save();X.translate(e.x,432);if(e.hit>0)X.globalAlpha=.45;X.strokeStyle=b?'#e30624':'#171318';X.fillStyle='#070709';X.lineWidth=b?12:8;X.lineCap='round';const q=Math.sin(t/180+e.id)*4;X.beginPath();X.arc(0,-(b?105:64)+q,b?31:20,0,7);X.fill();X.stroke();X.beginPath();X.moveTo(0,-(b?74:44)+q);X.lineTo(0,-18);X.moveTo(0,-55);X.lineTo(-32,-25);X.moveTo(0,-55);X.lineTo(35,-31);X.moveTo(0,-18);X.lineTo(-24,0);X.moveTo(0,-18);X.lineTo(26,0);X.stroke();X.fillStyle='#e30624';X.beginPath();X.arc(-7,-(b?108:67)+q,3,0,7);X.arc(7,-(b?108:67)+q,3,0,7);X.fill();if(b){X.strokeStyle='#e30624';X.lineWidth=7;for(let i=0;i<4;i++){X.beginPath();X.moveTo(0,-70);X.quadraticCurveTo((i-1.5)*34,-90-i*12,(i-1.5)*55,-55);X.stroke()}}X.fillStyle='#312a2d';X.fillRect(-28,b?-157:-101,56,6);X.fillStyle='#e30624';X.fillRect(-28,b?-157:-101,56*e.hp/e.max,6);X.restore()}
function world(t){const z=X.createLinearGradient(0,0,960,0);z.addColorStop(0,'#edeae2');z.addColorStop(.55,'#8c8782');z.addColorStop(1,'#050507');X.fillStyle=z;X.fillRect(0,0,960,540);X.globalAlpha=.16;X.strokeStyle='#111';for(let i=0;i<14;i++){X.beginPath();X.moveTo(i*83+(t/90)%83,60+(i%3)*45);X.lineTo(i*72-80,380);X.stroke()}X.globalAlpha=1;X.fillStyle='#0b0b0d';X.fillRect(0,432,960,108);X.fillStyle='#e30624';X.fillRect(0,432,960,5);X.save();X.translate(875,270);X.rotate(t/900);X.strokeStyle='#e30624';X.shadowColor='#e30624';X.shadowBlur=28;X.lineWidth=11;X.beginPath();X.ellipse(0,0,54,110,0,0,7);X.stroke();X.restore();G.enemies.forEach(e=>enemy(e,t));hero()}
function tick(t){const d=Math.min(2,(t-last)/16.67||1);last=t;if(mode==='playing'){let l=keys.has('KeyA')||keys.has('ArrowLeft'),r=keys.has('KeyD')||keys.has('ArrowRight');if(l){G.x-=4.4*d;G.f=-1}if(r){G.x+=4.4*d;G.f=1}G.x=Math.max(40,Math.min(910,G.x));if((keys.has('KeyW')||keys.has('ArrowUp')||keys.has('Space'))&&G.y>=432)G.vy=-12.5;G.vy+=.65*d;G.y=Math.min(432,G.y+G.vy*d);if(G.y>=432)G.vy=0;if(G.atk>0)G.atk-=d;if(G.form>0)G.form-=d;if(G.hurt>0)G.hurt-=d;G.enemies.forEach(e=>{if(e.hit>0)e.hit-=d;let dx=G.x-e.x;if(Math.abs(dx)>34)e.x+=Math.sign(dx)*(e.kind==='boss'?1.05:.72)*d;else if(G.hurt<=0){G.hp-=e.kind==='boss'?9:5;G.hurt=55;G.x-=Math.sign(dx)*25}});if(G.atk>10){let reach=(G.weapon==='spear'?108:72)*(G.form?1.35:1);G.enemies.forEach(e=>{let a=(e.x-G.x)*G.f;if(a>0&&a<reach&&e.hit<=0){e.hp-=G.form?34:(G.weapon==='spear'?22:15);e.hit=25;G.rage=Math.min(100,G.rage+12)}});G.atk=9}let dead=G.enemies.filter(e=>e.hp<=0);if(dead.length){G.shards+=dead.reduce((n,e)=>n+(e.kind==='boss'?5:1),0);G.enemies=G.enemies.filter(e=>e.hp>0)}if(!G.enemies.length&&!G.boss){G.boss=true;G.enemies=[{id:9,x:790,hp:210,max:210,kind:'boss',hit:0}]}if(G.boss&&!G.enemies.length&&G.x>820)ending(true);if(G.hp<=0)ending(false);updateHud()}world(t);requestAnimationFrame(tick)}
document.addEventListener('keydown',e=>{keys.add(e.code);if(['Space','ArrowUp','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='KeyJ')attack();if(e.code==='KeyQ')swap();if(e.code==='KeyE')transform()});document.addEventListener('keyup',e=>keys.delete(e.code));document.querySelector('[data-screen="story"]').onclick=()=>{mode='story';show('#story')};$('#start').onclick=start;$('#restart').onclick=start;$('#attack').onclick=attack;$('#swap').onclick=swap;$('#monster').onclick=transform;document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=()=>keys.add(b.dataset.key);b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key)});requestAnimationFrame(tick)})();

